name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mix_test:
    name: mix test (OTP ${{matrix.otp}}, Elixir ${{matrix.elixir}})
    runs-on: ubuntu-latest
    container: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-ubuntu-bionic-20200403
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.1.1
            otp: 17.5.6.10
          - elixir: 1.2.6
            otp: 18.3.4.11
          - elixir: 1.3.4
            otp: 18.3.4.11
          - elixir: 1.4.5
            otp: 18.3.4.11
          - elixir: 1.5.3
            otp: 18.3.4.11
          - elixir: 1.6.6
            otp: 19.3.6.13
          - elixir: 1.7.4
            otp: 19.3.6.13
          - elixir: 1.8.2
            otp: 20.3.8.26
          - elixir: 1.9.4
            otp: 20.3.8.26
          - elixir: 1.10.3
            otp: 21.3.8.16
          - elixir: 1.10.3
            otp: 23.0.2
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get --only test
    #   - run: mix coveralls.github
    # https://github.com/parroty/excoveralls#mix-coverallsgithub-post-coverage-from-github-actions
      - run: mix test

  check_formatted:
    name: Check formatted
    runs-on: ubuntu-latest
    container: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-alpine-3.11.6
    strategy:
      matrix:
        include:
          - elixir: 1.10.3
            otp: 23.0.2
    steps:
      - uses: actions/checkout@v2.3.1
      - run: mix format --check-formatted

  docs:
    runs-on: ubuntu-latest
    container: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-alpine-3.11.6
    strategy:
      matrix:
        include:
          - elixir: 1.10.3
            otp: 23.0.2
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          apk add git
          mix local.rebar --force
          mix local.hex --force
          mix deps.get --only docs
      - run: mix inch.report
        env:
          MIX_ENV: docs
